release_date: 2017-07-18

variables:
  - pkg_name: bzip2
  - pkg_ver: '1.0.6'

# Dependencies
dependencies:
  musl-libc:
    - headers
    - libs

prepare:
  - apk add tar gzip

# Source
source:
  # tar.gz: http://www.bzip.org/{pkg_ver}/{pkg_name}-{pkg_ver}.tar.gz
  tar.gz: https://downloads.sourceforge.net/project/bzip2/bzip2-{pkg_ver}.tar.gz

# Build stage
build:
  - make CC=gclang LDFLAGS="-static"
  - make install PREFIX={__INSTALL_DIR__}
